sudoku solution
Veronika-Chagina/cs102b pull request #5
Opened 2021-11-17 10:18 UTC by Veronika-Chagina

2021-12-30 17:31 UTC, anastasiiaCher requested changes
Верните в функции доктесты

2021-12-30 17:31 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return (-1, -1)
скобки не нужны

2022-01-05 09:52 UTC, Veronika-Chagina commented on homework02/sudoku.py
> +    return (-1, -1)
done

2022-01-17 06:35 UTC, anastasiiaCher reviewed
Доктесты не вернули

2022-12-31 20:14 UTC, closed without merging